# Generated by Django 3.1.1 on 2020-11-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
