# Generated by Django 3.1.1 on 2020-12-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_auto_20201206_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmatch',
            name='nextGame',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='roundNo',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
