# Generated by Django 3.1.1 on 2020-12-06 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_auto_20201206_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='bye',
        ),
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='lastGames',
        ),
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='nextGame',
        ),
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='roundNo',
        ),
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='teamnames',
        ),
    ]
