# Generated by Django 3.1.1 on 2020-12-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_auto_20201206_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='nextGame',
            field=models.IntegerField(default=0),
        ),
    ]
