# Generated by Django 3.1.1 on 2020-12-06 23:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_tournamentmatch_nextgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='bye',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='lastGames',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], null=True, size=None),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='roundNo',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='teamnames',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=[], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='nextGame',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
