# Generated by Django 3.1.1 on 2020-12-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_auto_20201206_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='no_of_players',
            field=models.IntegerField(choices=[(2, 2), (4, 4), (8, 8), (16, 16), (32, 32)]),
        ),
    ]
