# Generated by Django 3.1.1 on 2020-12-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_auto_20201207_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='wager',
            field=models.IntegerField(default=0),
        ),
    ]
