# Generated by Django 3.1.2 on 2020-11-03 01:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_adwatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='buynow',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
