# Generated by Django 3.1.2 on 2020-11-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_buynow_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='adwatch',
            name='name',
            field=models.CharField(default='username', max_length=1024),
        ),
    ]
