# Generated by Django 3.1.2 on 2020-11-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_adwatch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='adwatch',
            name='modelName',
            field=models.CharField(default='adWatch', max_length=100),
        ),
        migrations.AddField(
            model_name='buynow',
            name='modelName',
            field=models.CharField(default='buyNow', max_length=100),
        ),
    ]
