# Generated by Django 3.1.2 on 2020-11-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20201103_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='buynow',
            name='fullName',
            field=models.CharField(default='', max_length=1024, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='buynow',
            name='item',
            field=models.CharField(choices=[('Ps4', 'Ps4'), ('Ps4_Controller', 'Ps4 controller'), ('Xbox', 'Xbox'), ('Xbox_Controller', 'Xbox controller'), ('Madden', 'Madden'), ('Nba2k21', 'Nba2k21'), ('Gaming_Monitor', 'Gaming Monitor'), ('Gaming_Headset', 'Gaming Headset')], default='Ps4', max_length=20),
        ),
        migrations.AlterField(
            model_name='buynow',
            name='name',
            field=models.CharField(default='username', max_length=1024),
        ),
    ]
