# Generated by Django 3.1.2 on 2020-11-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20201104_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buynow',
            name='fullName',
            field=models.CharField(max_length=1024, verbose_name='Full name'),
        ),
    ]
