# Generated by Django 3.1.2 on 2020-11-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20201104_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adwatch',
            name='name',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='buynow',
            name='name',
            field=models.CharField(max_length=1024),
        ),
    ]
