# Generated by Django 3.1.2 on 2020-11-06 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20201104_0715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adwatch',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='buynow',
            old_name='name',
            new_name='username',
        ),
    ]
