# Generated by Django 3.1.2 on 2020-11-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameMatchResult', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlegamematchresult',
            name='modelName',
            field=models.CharField(default='singleGameMatchResult', max_length=100),
        ),
    ]
